import './globals.css'
import { Inter } from 'next/font/google';
import '../../public/assets/icon/fontawesome-free-6.4.0-web/fontawesome-free-6.4.0-web/css/all.min.css'
import Providers from '@/globalredux/provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'HHQ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
